In [138]:
import numpy as np

In [139]:
def pivot(A, BV, r, c):
    A = np.array(A)
    A = A.astype(float)
    A[r, :] = A[r, :] / A[r, c]
    rows = len(A)
    for i in range(rows):
        if i != r:
            A[i, :] = A[i, :] - A[i, c] * A[r, :]
    BV[r - 1] = c
    return A, BV

In [160]:
A = [
    [1, -5, -4, -3, 0, 0, 0, 0],
    [0, 2, 3, 1, 1, 0, 0, 5],
    [0, 4, 1, 2, 0, 1, 0, 11],
    [0, 3, 4, 2, 0, 0, 1, 8]
]

BV = [4, 5, 6]

def simplex_method(A, BV):
    matrix = np.array(A)
    matrix = matrix.astype(float)
    print matrix
    basic_var_pos = BV[:]
    
    while True:
        
        temp = matrix[0][ matrix[0] != 0 ]
        if all(i > 0 for i in temp[1 : len(temp)]):
            break
        
        idx_min = np.argmin(matrix[0])
        print 'index : {}'.format(idx_min)
        
        check_pivot = map(lambda row: row[-1]/row[idx_min], matrix[1: len(matrix)])
        check_pivot = np.array(check_pivot)
        print 'check pivot : {}'.format(check_pivot)
        
        row_to_pivot = np.where(check_pivot == min(check_pivot[ check_pivot >= 0]))[0][0] + 1
        print 'row: {}'.format(row_to_pivot)
        
        matrix, basic_var_pos = pivot(matrix, basic_var_pos, row_to_pivot, idx_min) 
        
        print matrix, basic_var_pos
        

In [141]:
simplex_method(A, BV)

[[ 1. -5. -4. -3.  0.  0.  0.  0.]
 [ 0.  2.  3.  1.  1.  0.  0.  5.]
 [ 0.  4.  1.  2.  0.  1.  0. 11.]
 [ 0.  3.  4.  2.  0.  0.  1.  8.]]
index : 1
check pivot : [2.5, 2.75, 2.6666666666666665]
row: 1
[[ 1.   0.   3.5 -0.5  2.5  0.   0.  12.5]
 [ 0.   1.   1.5  0.5  0.5  0.   0.   2.5]
 [ 0.   0.  -5.   0.  -2.   1.   0.   1. ]
 [ 0.   0.  -0.5  0.5 -1.5  0.   1.   0.5]] [1, 5, 6]
index : 3
check pivot : [5.0, inf, 1.0]
row: 3
[[ 1.  0.  3.  0.  1.  0.  1. 13.]
 [ 0.  1.  2.  0.  2.  0. -1.  2.]
 [ 0.  0. -5.  0. -2.  1.  0.  1.]
 [ 0.  0. -1.  1. -3.  0.  2.  1.]] [1, 5, 3]
2


/anaconda3/envs/opt_research/lib/python2.7/site-packages/ipykernel_launcher.py:26: RuntimeWarning: divide by zero encountered in double_scalars


In [91]:
test = [
    [1, -5, -4, -3, 0, 0, 0, 0],
    [0, 2, 3, 1, 1, 0, 0, 5],
    [0, 4, 1, 2, 0, 1, 0, 11],
    [0, 3, 4, 2, 0, 0, 1, 8]
]
test = np.array(test)
test = test.astype(float)
test

array([[ 1., -5., -4., -3.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  3.,  1.,  1.,  0.,  0.,  5.],
       [ 0.,  4.,  1.,  2.,  0.,  1.,  0., 11.],
       [ 0.,  3.,  4.,  2.,  0.,  0.,  1.,  8.]])

In [161]:
dual_problem = np.array([
    [1, -10, -6, -15, 0, 0, 0, 0],  # --> objective function
    [0, 1, 1, 3, 1, 0, 0, 2],  # --> constraint 1
    [0, -1, -2, -4, 0, 1, 0, 3],  # --> constraint 2
    [0, 1, 3, 5, 0, 0, 1, 4]  # --> constraint 3
])
basic = [4, 5, 6]
simplex_method(dual_problem, basic)

[[  1. -10.  -6. -15.   0.   0.   0.   0.]
 [  0.   1.   1.   3.   1.   0.   0.   2.]
 [  0.  -1.  -2.  -4.   0.   1.   0.   3.]
 [  0.   1.   3.   5.   0.   0.   1.   4.]]
index : 3
check pivot : [ 0.66666667 -0.75        0.8       ]
row: 1
[[ 1.         -5.         -1.          0.          5.          0.
   0.         10.        ]
 [ 0.          0.33333333  0.33333333  1.          0.33333333  0.
   0.          0.66666667]
 [ 0.          0.33333333 -0.66666667  0.          1.33333333  1.
   0.          5.66666667]
 [ 0.         -0.66666667  1.33333333  0.         -1.66666667  0.
   1.          0.66666667]] [3, 5, 6]
index : 1
check pivot : [ 2. 17. -1.]
row: 1
[[ 1.  0.  4. 15. 10.  0.  0. 20.]
 [ 0.  1.  1.  3.  1.  0.  0.  2.]
 [ 0.  0. -1. -1.  1.  1.  0.  5.]
 [ 0.  0.  2.  2. -1.  0.  1.  2.]] [1, 5, 6]
2


In [163]:
test2 = [
    [1, -10, -11, 0, 0, 0, 0],
    [0, 3, 4, 1, 0, 0, 9],
    [0, 5, 2, 0, 1, 0, 8],
    [0, 1, -2, 0, 0, 1, 1]
]
basic = [3, 4, 5]
simplex_method(test2, basic)

[[  1. -10. -11.   0.   0.   0.   0.]
 [  0.   3.   4.   1.   0.   0.   9.]
 [  0.   5.   2.   0.   1.   0.   8.]
 [  0.   1.  -2.   0.   0.   1.   1.]]
index : 2
check pivot : [ 2.25  4.   -0.5 ]
row: 1
[[ 1.   -1.75  0.    2.75  0.    0.   24.75]
 [ 0.    0.75  1.    0.25  0.    0.    2.25]
 [ 0.    3.5   0.   -0.5   1.    0.    3.5 ]
 [ 0.    2.5   0.    0.5   0.    1.    5.5 ]] [2, 4, 5]
index : 1
check pivot : [3.  1.  2.2]
row: 2
[[ 1.          0.          0.          2.5         0.5         0.
  26.5       ]
 [ 0.          0.          1.          0.35714286 -0.21428571  0.
   1.5       ]
 [ 0.          1.          0.         -0.14285714  0.28571429  0.
   1.        ]
 [ 0.          0.          0.          0.85714286 -0.71428571  1.
   3.        ]] [2, 1, 5]
2
